networks:
  dev-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.200.0/29
services:
  mikrotik-scraper:
    build: .
    container_name: mikrotik-scraper
    volumes:
      - .:/app
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dev-net